### ISSUE TITLE
TypeError: forEachAsync is not a function

### ISSUE THREAD

**Issue by xzwc** [yalishizhude/api-document#13]
Hi,when I execute “npm start”,it reports as follws: 

TypeError: forEachAsync is not a function
    at Walker._wReadFiles (/Users/zhanghaoye/Desktop/NodeProject/api-document/api-document/node_modules/hbs-utils/node_modules/walk/lib/walk.js:153:7)
    at Walker._wReaddirHandler (/Users/zhanghaoye/Desktop/NodeProject/api-document/api-document/node_modules/hbs-utils/node_modules/walk/lib/walk.js:166:10)
    at /Users/zhanghaoye/Desktop/NodeProject/api-document/api-document/node_modules/hbs-utils/node_modules/walk/lib/walk.js:225:10
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! api-document-server@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api-document-server@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the api-document-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs api-document-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls api-document-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhanghaoye/Desktop/NodeProject/api-document/api-document/npm-debug.log

**Comment by xzwc** [comment]
When it occurs  "[2016-10-18 11:15:03.425] [ERROR] console - js-bson: Failed to load c++ bson extension, using pure JS version",I reinstall the bson module,so the upper problem occurs.

**Comment by yalishizhude** [comment]
那个bson的error是windows平台的错误，对功能没影响，可以忽略~
目前来看应该是你执行npm intall的时候有些模块没有正确安装所致
