### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by liugenpeng** [yalishizhude/api-document#2]

**Comment by liugenpeng** [comment]
![image](https://cloud.githubusercontent.com/assets/4234063/12145407/f39dbebe-b4c8-11e5-94cc-0793feb5176b.png)

**Comment by yalishizhude** [comment]
操作什么的时候出现的？

**Comment by liugenpeng** [comment]
登录之后就报错了

**Comment by yalishizhude** [comment]
方便的话加qq我远程看一下~

**Comment by liugenpeng** [comment]
已发邮件

**Comment by yalishizhude** [comment]
bower install angular#1.2 
已解决并更新代码~
